### ISSUE TITLE
Operationplan's attribute not saved

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#618]
### Discussed in https://github.com/frePPLe/frepple/discussions/617

<div type='discussions-op-text'>

<sup>Originally posted by **matteocarcano** November 14, 2023</sup>
Hi,
I would like to create operationplan's attribuite but when i do i can edit the new field but if i save changes i lost what i've just written, in other words frepple doesn't save changes. If i do the same thing with item's attribute it works correctly. </div>

**Comment by jdetaeye** [comment]
Fixed

**Comment by matteocarcano** [comment]
Hi, 
i've tested after 8.30 release but bug is not fixed.

I've the same problem: Frepple doesn't save custom attribute changes.
